#!/usr/bin/env python3
"""Which files count as the project, decided once for every script in this folder.

detect_stack, scan_repo, and check_boundaries each walk the repository. They
must agree on what to skip (dependency and build folders, dot-directories),
what a test file looks like, and how much to read, or the same project shows
different shapes to different tools. Import from here; do not copy.

Standard library only. Reads files; never writes.
"""

from __future__ import annotations

import functools
import os
import re
import subprocess
from pathlib import Path
from typing import NamedTuple

# Directories that hold dependencies, build output, or tool caches. Walking them
# is slow and tells us nothing about the project's own design.
SKIP_DIRS = frozenset({
    ".git", ".hg", ".svn", ".idea", ".vscode", ".vs",
    "node_modules", "bower_components", "jspm_packages", "vendor",
    "__pycache__", ".venv", "venv", "env", ".tox", ".nox", ".mypy_cache",
    ".pytest_cache", ".ruff_cache", ".gradle", ".dart_tool", ".terraform",
    "bin", "obj", "build", "dist", "out", "target", "_build", "deps",
    "coverage", "htmlcov", ".next", ".nuxt", ".svelte-kit", ".parcel-cache",
    "Pods", "Carthage", ".cargo", ".stack-work", "cmake-build-debug", "migrations",
    "wp-admin", "wp-includes",
})

# A folder a framework owns, pruned only where the framework's own layout proves it:
# Unity's Library/Temp/Logs/UserSettings are rebuildable caches beside Assets and
# ProjectSettings, a Drupal docroot's composer-installed core, or a modules, themes, or
# profiles folder's composer-installed contrib, are not the project's code, and neither is
# Flutter's generated {windows,linux,macos}/flutter/ephemeral or ios/Flutter/ephemeral.
# (sibling folder names that must all be present, folder names to prune, parent folder
# names one of which must hold them: empty for any)
FRAMEWORK_OWNED_DIRS = (
    (frozenset({"Assets", "ProjectSettings"}), frozenset({"Library", "Temp", "Logs", "UserSettings"}),
     frozenset()),
    (frozenset({"core", "modules", "sites"}), frozenset({"core"}), frozenset()),
    (frozenset({"contrib", "custom"}), frozenset({"contrib"}), frozenset()),
    (frozenset(), frozenset({"ephemeral"}), frozenset({"flutter", "Flutter"})),
)

TEST_DIR_NAMES = frozenset({
    "test", "tests", "spec", "specs", "__tests__", "testing",
    "unittest", "unittests", "test_suite", "integration-tests",
})

TEST_FILE_PATTERN = re.compile(
    r"(^test_|_test\.|\.test\.|\.spec\.|_spec\.|Tests?\.|Spec\.)", re.IGNORECASE
)
# A .NET test project: `Shop.Tests/`, `Shop.UnitTests/`, `Shop.IntegrationTest/`, `Shop.Test/`.
TEST_PROJECT_PATTERN = re.compile(r"\.(?:Unit|Integration)?Tests?$", re.IGNORECASE)

# Folders named for no concept, a place to put code rather than what the code is about.
# `tools` is left out: it is often the domain word itself (an MCP server's tools, build tooling).
JUNK_DRAWER_NAMES = frozenset({
    "utils", "util", "helpers", "helper", "common", "shared", "misc", "miscellaneous", "general",
    "stuff", "core_utils", "lib_utils", "extras",
})

GENERATED_MARKERS = (
    "generated by", "auto-generated", "autogenerated", "do not edit",
    "code generated by", "@generated",
)
# Prose that may describe the file's own subject, a Python module docstring or PowerShell
# help, says a generator wrote the file only through these: "invoices generated by the
# billing run" is hand-written.
STRONG_GENERATED_MARKERS = ("do not edit", "auto-generated", "autogenerated", "@generated",
                            "code generated by")

# Files a generator owns by name: .NET designers, source generators, protobuf stubs, and
# minified or bundled scripts and styles.
GENERATED_NAME = re.compile(r"\.(?:designer|g|g\.i|generated)\.\w+$|_pb2\.py$|\.pb\.go$"
                            r"|\.min\.(?:js|mjs|css)$|\.bundle\.js$",
                            re.IGNORECASE)
GENERATED_HEAD_LINES = 15

# A generator's header opens the file, before any code: line and block comments, after a
# PHP open tag or, in C-family and C# files, a directive such as `#pragma` or `#include`.
_LINE_COMMENT = re.compile(r"^(?://|--|#)")
_BLOCK_COMMENTS = (("/*", "*/"), ("<!--", "-->"))
_PHP_OPEN_TAG = re.compile(r"^<\?(?:php)?$")
_DIRECTIVE_SUFFIXES = frozenset({".c", ".h", ".cc", ".cpp", ".cxx", ".hpp", ".hh", ".m", ".mm", ".cs"})
_PYTHON_DOCSTRING = re.compile(r"^[rRuUbB]{0,2}(\"{3}|'{3})")
_PYTHON_SUFFIXES = frozenset({".py", ".pyi"})
_POWERSHELL_SUFFIXES = frozenset({".ps1", ".psm1", ".psd1"})

MAX_FILE_BYTES = 2_000_000
MAX_FILES_SCANNED = 40000
# Matches the timeout scan_repo.py and map_structure.py already use for their own
# git subprocess calls.
_GIT_TIMEOUT_SECONDS = 30
_GITLINK_MODE = "160000"


class Walk(NamedTuple):
    """Root-relative posix paths in walk order, and whether the cap cut the walk short."""

    paths: list
    truncated: bool


def is_skippable(directory_name: str) -> bool:
    return directory_name in SKIP_DIRS or (
        directory_name.startswith(".") and directory_name != ".github"
    )


def walk(root: Path, suffixes=None, names=frozenset()) -> Walk:
    """Every project file under root, optionally only those with the given suffixes or names.

    Inside a git work tree with `git` on PATH, the list comes from `git ls-files`
    (tracked files plus untracked ones `.gitignore` doesn't exclude), so a project's
    own ignored folders - vendored code, build output, a gitignored `books/` - drop
    out before the pruning below even runs. Outside a work tree, without `git`, if
    `root` itself is ignored by an enclosing repository, or if the command fails for
    any other reason, this falls back to `os.walk`; either way the same SKIP_DIRS,
    dot-folder, and framework-owned-folder pruning and the same suffix/name filters
    apply, in the same order `os.walk` would visit a directory: a directory's own
    files before its subdirectories, both sorted by name.

    Stops at MAX_FILES_SCANNED and says so, so a caller never mistakes a partial
    walk for the whole project.
    """
    git_walk = _walk_git(root, suffixes, names)
    if git_walk is not None:
        return git_walk
    return _walk_os(root, suffixes, names)


def _pruned_os_walk(start: Path):
    """(directory, sorted file names) from `os.walk`, with SKIP_DIRS, dot-folder, and
    framework-owned-folder pruning applied and subdirectories visited in name order.
    """
    for current_dir, subdirs, filenames in os.walk(start):
        pruned = _pruned_child_names(os.path.basename(current_dir), subdirs)
        subdirs[:] = sorted(name for name in subdirs
                             if not is_skippable(name) and name not in pruned)
        yield current_dir, sorted(filenames)


def _walk_os(root: Path, suffixes, names) -> Walk:
    """`walk()`'s fallback: the filesystem walked directly with `os.walk`."""
    paths: list = []
    for current_dir, filenames in _pruned_os_walk(root):
        for filename in filenames:
            path = Path(current_dir) / filename
            if suffixes is not None and path.suffix.lower() not in suffixes and filename not in names:
                continue
            if len(paths) >= MAX_FILES_SCANNED:
                return Walk(paths, True)
            try:
                paths.append(path.relative_to(root).as_posix())
            except ValueError:
                continue
    return Walk(paths, False)


def _pruned_child_names(directory_basename: str, child_dirs) -> frozenset:
    """Framework-owned subdirectory names to drop from `child_dirs`, decided by which
    sibling directories are present and what the directory itself is named. Shared by
    the `os.walk` fallback and the git-backed walk so the two rulesets can never drift
    apart.
    """
    child_dirs = frozenset(child_dirs)
    return frozenset().union(*(
        prune_names for required, prune_names, parents in FRAMEWORK_OWNED_DIRS
        if required <= child_dirs and (not parents or directory_basename in parents)
    ))


def _walk_git(root: Path, suffixes, names):
    """`walk()`'s result read from `git ls-files`, or None when `root` is not a git
    work tree, `git` is missing, `root` itself is ignored by an enclosing repository,
    or the command fails for any other reason.
    """
    raw = _run_git_ls_files(root)
    if raw is None:
        return None
    entries = [entry for entry in raw.split("\0") if entry]
    if not entries and _root_ignore_makes_list_unusable(root):
        return None
    file_paths = _expand_to_file_paths(root, entries)
    children_by_dir = _raw_subdirectories(file_paths)
    files_by_dir = _files_by_directory(file_paths)
    return _walk_pruned_tree(root, children_by_dir, files_by_dir, suffixes, names)


def _run_git_ls_files(root: Path):
    """The raw, null-separated `git ls-files -s` output for `root`, decoded, or None
    when git can't be used. Never raises.

    `-s` also reports each `--cached` entry's file mode, so a submodule gitlink
    (mode 160000) can be told apart from a regular file without stat-ing anything.
    Run with `cwd=root`, `git ls-files` on its own (no pathspec) already limits
    itself to files at or under `root` and reports them relative to it, even when
    `root` is a subfolder of a larger work tree.
    """
    listing = _run_git(["ls-files", "-s", "--cached", "--others", "--exclude-standard", "-z"], root)
    if listing is None:
        return None
    # A path can carry bytes that are not valid utf-8 (a filename from another
    # encoding); surrogateescape keeps them round-trippable instead of collapsing
    # them to the replacement character the way errors="replace" would.
    return listing.decode("utf-8", errors="surrogateescape")


def _root_ignore_makes_list_unusable(root: Path) -> bool:
    """Whether an empty `git ls-files` result means `root` itself is ignored by an
    enclosing repository - its own content is invisible to git, not actually absent.

    The root's own path is checked from the repository's top with `git check-ignore`
    (checking `.` from inside the root is unreliable: a `data/*` pattern reports it as
    ignored). Exit 1 means the root is not ignored, so the empty list is the truth -
    every file in it is ignored - and any other answer falls back to `os.walk`.
    """
    location = _run_git(["rev-parse", "--show-toplevel", "--show-prefix"], root)
    if location is None:
        return True
    lines = location.decode("utf-8", errors="surrogateescape").splitlines()
    prefix = lines[1].rstrip("/") if len(lines) > 1 else ""
    if not prefix:
        return False  # the repository's top is never ignored
    ignored = _run_git(["check-ignore", "--quiet", prefix], Path(lines[0]), exit_code=True)
    return ignored != 1


def _run_git(arguments: list, cwd: Path, exit_code: bool = False):
    """`git <arguments>` run in cwd: its stdout bytes (None on failure), or with
    `exit_code` its exit code (None when git could not run). Never raises.
    """
    try:
        result = subprocess.run(["git", *arguments], cwd=cwd, capture_output=True,
                                timeout=_GIT_TIMEOUT_SECONDS)
    except (OSError, subprocess.SubprocessError):
        return None
    if exit_code:
        return result.returncode
    return result.stdout if result.returncode == 0 else None


def _parse_ls_files_entry(entry: str) -> tuple:
    """(kind, path) for one `git ls-files -s --cached --others --exclude-standard -z`
    entry.

    "gitlink" is a submodule (mode 160000, from `--cached`); "nested" is an
    untracked directory git didn't descend into because it holds its own repository
    (reported with a trailing slash, from `--others`); either way git lists none of
    the files inside. Otherwise "file" - a path git believes is a file; its existence
    is confirmed only if it survives suffix/name filtering, since a tracked file can
    still be gone from the working tree.
    """
    left, tab, path = entry.partition("\t")
    if tab:
        mode = left.split(" ", 1)[0]
        return ("gitlink", path) if mode == _GITLINK_MODE else ("file", path)
    if entry.endswith("/"):
        return ("nested", entry[:-1])
    return ("file", entry)


def _is_safe_relative_path(path: str) -> bool:
    """Whether `path` stays under root: false for one that climbs out of it or is
    already absolute, which `git ls-files` should never emit here but a broken
    pathspec elsewhere might.
    """
    posix_path = path.replace("\\", "/")
    return not (posix_path.startswith("/") or posix_path.split("/", 1)[0] == "..")


def _expand_to_file_paths(root: Path, entries: list) -> list:
    """Every git-reported entry, as concrete root-relative file paths.

    A submodule gitlink or an untracked nested repository is expanded by walking it
    directly with `os.walk` (the same pruning `_walk_os` applies), since git itself
    won't list the files inside either one.
    """
    file_paths = []
    for entry in entries:
        kind, path = _parse_ls_files_entry(entry)
        if not _is_safe_relative_path(path):
            continue
        if kind == "file":
            file_paths.append(path)
        else:
            file_paths.extend(_os_walk_raw_paths(root, path))
    # A conflicted file appears once per merge stage in `ls-files -s --cached`.
    return list(dict.fromkeys(file_paths))


def _os_walk_raw_paths(root: Path, start_relative: str) -> list:
    """Every file under root/start_relative, root-relative posix paths, pruned the
    same way `_walk_os` prunes - unfiltered by suffix or name, for merging into a
    git-derived path list.
    """
    paths: list = []
    for current_dir, filenames in _pruned_os_walk(root / start_relative):
        for filename in filenames:
            path = Path(current_dir) / filename
            try:
                paths.append(path.relative_to(root).as_posix())
            except ValueError:
                continue
    return paths


def _raw_subdirectories(paths: list) -> dict:
    """Every directory's immediate child directory names, as an unfiltered `os.walk`
    would see them, keyed by the directory's own root-relative posix path (`""` for
    root).
    """
    children: dict = {}
    for path in paths:
        parts = path.split("/")
        current = ""
        for part in parts[:-1]:
            children.setdefault(current, set()).add(part)
            current = f"{current}/{part}" if current else part
    return children


def _files_by_directory(paths: list) -> dict:
    """Every directory's own files, keyed the same way as `_raw_subdirectories`."""
    files: dict = {}
    for path in paths:
        directory, _, filename = path.rpartition("/")
        files.setdefault(directory, []).append(filename)
    return files


def _existing_subdirectories(root: Path, directory: str) -> frozenset:
    """Immediate child directory names that exist on disk under root/directory.

    A framework-owned-folder rule's required sibling (a Unity `ProjectSettings/`, a
    Drupal `modules/custom/`) must still count as present even when git lists none
    of its files - because it is empty, or every file inside happens to be
    gitignored too - or the rule would silently stop firing for a git-backed walk.
    """
    try:
        with os.scandir(root / directory) as entries:
            return frozenset(entry.name for entry in entries if entry.is_dir())
    except OSError:
        return frozenset()


def _walk_pruned_tree(root: Path, children_by_dir: dict, files_by_dir: dict, suffixes, names) -> Walk:
    """A directory tree built from a flat path list, visited the way `os.walk` visits
    the filesystem: a directory's own files before its subdirectories, both sorted by
    name, with the same SKIP_DIRS/dot-folder/framework-owned pruning.
    """
    paths: list = []
    truncated = False

    def visit(directory: str) -> bool:
        """Emit `directory`'s kept files, then recurse into its kept subdirectories.
        Returns True once the cap is hit, so the caller stops descending."""
        nonlocal truncated
        for filename in sorted(files_by_dir.get(directory, ())):
            if suffixes is not None and Path(filename).suffix.lower() not in suffixes and filename not in names:
                continue
            full_relative = f"{directory}/{filename}" if directory else filename
            # Stat only a file that already cleared the filter above and is about to
            # be emitted: git can still list a tracked file that is gone on disk.
            if not (root / full_relative).is_file():
                continue
            if len(paths) >= MAX_FILES_SCANNED:
                truncated = True
                return True
            paths.append(full_relative)
        child_dirs = children_by_dir.get(directory, frozenset())
        basename = directory.rpartition("/")[2] if directory else root.name
        pruning_siblings = frozenset(child_dirs) | _existing_subdirectories(root, directory)
        pruned = _pruned_child_names(basename, pruning_siblings)
        for child in sorted(child_dirs):
            if is_skippable(child) or child in pruned:
                continue
            if visit(f"{directory}/{child}" if directory else child):
                return True
        return False

    visit("")
    return Walk(paths, truncated)


def is_test_path(relative_path: str) -> bool:
    parts = relative_path.split("/")
    if any(part.lower() in TEST_DIR_NAMES or TEST_PROJECT_PATTERN.search(part) for part in parts[:-1]):
        return True
    return bool(TEST_FILE_PATTERN.search(parts[-1]))


def _block_opener(stripped: str, suffix: str):
    """(opener, closer, is_prose) when the line opens a block comment, a Python module
    docstring, or a PowerShell `<# #>` help block; else None."""
    for opener, closer in _BLOCK_COMMENTS:
        if stripped.startswith(opener):
            return opener, closer, False
    if suffix in _POWERSHELL_SUFFIXES and stripped.startswith("<#"):
        return "<#", "#>", True
    docstring = _PYTHON_DOCSTRING.match(stripped) if suffix in _PYTHON_SUFFIXES else None
    if docstring:
        return docstring.group(0), docstring.group(1), True
    return None


def _opening_text(text: str, suffix: str) -> tuple:
    """(comments, prose) before a file's first line of code, lowercased.

    Comments are line and block comments; prose is a Python module docstring or a
    PowerShell `<# #>` help block, which may describe the file's own subject.
    """
    comments, prose = [], []
    closer, block = None, comments
    for line in text.lstrip("\ufeff").split("\n", GENERATED_HEAD_LINES)[:GENERATED_HEAD_LINES]:
        stripped = line.strip()
        if closer:
            block.append(stripped)
            closer = None if closer in stripped else closer
            continue
        if not stripped or _PHP_OPEN_TAG.match(stripped):
            continue
        opened = _block_opener(stripped, suffix)
        if opened:
            opener, closer, is_prose = opened
            block = prose if is_prose else comments
            block.append(stripped)
            closer = None if closer in stripped[len(opener):] else closer
        elif stripped.startswith("#") and suffix in _DIRECTIVE_SUFFIXES:
            continue            # a preprocessor directive, not a comment
        elif _LINE_COMMENT.match(stripped):
            comments.append(stripped)
        else:
            break
    return "\n".join(comments).lower(), "\n".join(prose).lower()


def is_generated(relative_path: str, text: str) -> bool:
    """Whether a generator owns the file: by its name, or by a marker in the comment
    that opens it.

    Generated code is not the project's design; judging its structure would only
    report the generator's choices. A marker anywhere else is prose: a docstring
    saying "invoices generated by the billing run" is hand-written code, though one
    saying "do not edit" is not.
    """
    if GENERATED_NAME.search(relative_path):
        return True
    comments, prose = _opening_text(text, Path(relative_path).suffix.lower())
    return (any(marker in comments for marker in GENERATED_MARKERS)
            or any(marker in prose for marker in STRONG_GENERATED_MARKERS))


@functools.lru_cache(maxsize=None)
def _glob_regex(pattern: str) -> re.Pattern:
    normalized = pattern.replace("\\", "/").lower()
    parts = []
    index = 0
    while index < len(normalized):
        if normalized.startswith("**/", index):
            parts.append("(?:.*/)?")
            index += 3
        elif normalized.startswith("/**", index) and index + 3 == len(normalized):
            parts.append("(?:/.*)?")
            index += 3
        elif normalized.startswith("**", index):
            parts.append(".*")
            index += 2
        elif normalized[index] == "*":
            parts.append("[^/]*")
            index += 1
        elif normalized[index] == "?":
            parts.append("[^/]")
            index += 1
        else:
            parts.append(re.escape(normalized[index]))
            index += 1
    return re.compile("^" + "".join(parts) + "$")


def glob_match(pattern: str, relative_path: str) -> bool:
    """Whether a root-relative path matches a glob, ignoring case.

    `**/` spans zero or more directories and a trailing `/**` everything below,
    while `*` and `?` never cross a slash. fnmatch lets `*` cross slashes, which
    makes `**/middleware/**` miss a top-level `middleware/` folder.
    """
    return bool(_glob_regex(pattern).match(relative_path.replace("\\", "/").lower()))


def literal_weight(pattern: str) -> int:
    """How specific a glob is: its characters that are neither wildcards nor slashes."""
    return sum(1 for character in pattern if character not in "*?/\\")


def read_text(path: Path) -> str | None:
    """The file's text, or None when it is unreadable or too large to be source."""
    try:
        if path.stat().st_size > MAX_FILE_BYTES:
            return None
        # utf-8-sig drops a byte-order mark: Windows tools write one, and it would
        # otherwise sit in front of the first declaration.
        with path.open("r", encoding="utf-8-sig", errors="replace") as handle:
            return handle.read()
    except OSError:
        return None
