/**
 * ============================================================================
 *  <task-id> — <one-line description of what this firmware does>
 * ============================================================================
 *
 *  Board  : <board>            MCU : <part number>
 *  Design : see <task-id>-design-dossier.md   (pin map §3, CubeMX settings §6)
 *
 *  HOW TO USE THIS FILE
 *  --------------------
 *  This is reference code, not a drop-in replacement for your generated main.c.
 *  Configure the project in CubeMX per dossier §6, generate, then copy each block
 *  below into the matching USER CODE marker in your own main.c. The markers here
 *  are named exactly as CubeMX emits them.
 *
 *  Generated MX_*_Init() bodies are deliberately NOT reproduced — yours will differ
 *  in ordering and comments, and overwriting them causes drift the next time you
 *  regenerate.
 *
 *  ASSUMPTIONS BAKED INTO THIS CODE
 *  --------------------------------
 *   - <e.g. LED is active high on PG13 — invert the writes if your board differs>
 *   - <e.g. timer clock is 90 MHz; if you change the PLL, recompute PSC/ARR>
 * ============================================================================
 */

/* USER CODE BEGIN Includes */
#include <stdio.h>
#include <string.h>
#include <stdbool.h>
/* USER CODE END Includes */

/* USER CODE BEGIN PTD */
/* Application states. An explicit enum beats nested boolean flags as soon as there
   are three or more modes — it makes the illegal combinations unrepresentable. */
typedef enum {
    ST_<...>,
} app_state_t;
/* USER CODE END PTD */

/* USER CODE BEGIN PD */
#define <CONSTANT>_MS      <value>   /* <why this value — cite dossier §5 if computed> */
#define DEBOUNCE_MS        <value>   /* <mechanical switch bounce window vs deliberate-press intent> */
/* USER CODE END PD */

/* USER CODE BEGIN PV */
/* Shared with an ISR -> volatile, so the compiler reloads it every read instead of
   caching it in a register across the loop. */
volatile uint8_t  flag_<event> = 0;

/* Main-loop-only state: no volatile needed. */
static uint32_t   t_<activity> = 0;
static app_state_t state = ST_<...>;
/* USER CODE END PV */

/* USER CODE BEGIN PFP */
static void <helper>(void);
/* USER CODE END PFP */

/* USER CODE BEGIN 0 */
/* Helper implementations. Keep anything longer than a few lines out of main(). */
static void <helper>(void)
{
    /* ... */
}
/* USER CODE END 0 */


int main(void)
{
    HAL_Init();
    SystemClock_Config();       /* dossier §5 — a failure here ends in Error_Handler() */

    MX_GPIO_Init();             /* generated by CubeMX — settings in dossier §6 */
    /* MX_<PERIPH>_Init();      generated by CubeMX */

    /* USER CODE BEGIN 2 */
    /* CubeMX initialises peripherals but does not start most of them.
       Everything that needs arming goes here, once, before the loop. */

    /* <e.g. HAL_TIM_Base_Start_IT(&htim3);  — _IT variant: enables the update interrupt> */
    /* <e.g. HAL_UART_Receive_IT(&huart1, &rx_byte, 1); — arm the first byte> */

    /* USER CODE END 2 */

    /* USER CODE BEGIN WHILE */
    while (1)
    {
        uint32_t now = HAL_GetTick();

        /* --- activity 1: <description> ------------------------------------ */
        /* `now - t >= period` is wrap-safe across the uint32_t rollover (~49.7 days);
           `now >= t + period` is not. Always use the subtraction form. */
        if (now - t_<activity> >= <CONSTANT>_MS) {
            t_<activity> = now;
            /* ... */
        }

        /* --- activity 2: react to an ISR event ---------------------------- */
        /* The ISR only set a flag. The real work happens here, in thread context,
           where blocking calls and longer processing are safe. */
        if (flag_<event>) {
            flag_<event> = 0;
            /* ... */
        }

        /* --- state machine (if the task has modes) ------------------------ */
        switch (state) {
            case ST_<...>:
                /* ... */
                break;
            default:
                break;
        }
    }
    /* USER CODE END WHILE */
}


/* USER CODE BEGIN 4 */
/* ---------------------------------------------------------------------------
 * HAL callbacks.
 *
 * These are declared __weak in the driver; defining them here overrides the stubs.
 * A misspelled name compiles cleanly and is simply never called — if a callback
 * "does not fire", check the spelling before anything else.
 *
 * One callback serves every instance of a peripheral, so always check ->Instance.
 *
 * ISR rules: set a flag or move one datum, then return. No HAL_Delay, no blocking
 * transmit, no printf, no loops.
 * --------------------------------------------------------------------------- */

void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin)
{
    if (GPIO_Pin == <BTN>_Pin) {
        /* Time-based debounce: reject edges arriving within DEBOUNCE_MS of the last
           accepted one. Enough for a mechanical switch; a hardware RC filter or a
           sampled-state filter is the sturdier option if bounce is severe. */
        static uint32_t last_edge = 0;
        uint32_t now = HAL_GetTick();
        if ((now - last_edge) > DEBOUNCE_MS) {
            last_edge = now;
            flag_<event> = 1;
        }
    }
}

void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim)
{
    if (htim->Instance == TIM<n>) {
        /* ... */
    }
}

void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart)
{
    if (huart->Instance == USART<n>) {
        /* ... */
        HAL_UART_Receive_IT(huart, &rx_byte, 1);  /* re-arm, or reception stops here */
    }
}

/* USER CODE END 4 */


/* USER CODE BEGIN Error_Handler_Debug */
/* The generated Error_Handler() is a silent infinite loop, which is indistinguishable
   from "the board is dead". Make the failure visible — a fast blink on a known LED
   written directly to the port register, since HAL may not be usable at this point. */
/* USER CODE END Error_Handler_Debug */
